# Site settings
title: Theodore LaGrow Online
email: tjlagrow@gmail.com
description: >
  This is the website of Theodore LaGrow. Created by yours truly!
baseurl: ""                       # the subpath of your site, e.g. /blog/
url: "https://tjlagrow.github.io" # the base hostname & protocol for your site
github_username: tjlagrow

name: Theodore LaGrow
timezone: America/New_York        # more precise than "EST"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge

permalink: pretty

# Collections
collections:
  newsletters:
    output: true
    permalink: /newsletter/:name/
